#if defined _ugmp_included
	#endinput
#endif
#define _ugmp_included

#if defined _samp_included
	#error Including a_samp is deprecated. Please include a_ugmp.
#endif

/*
	a_samp
	By the SA-MP team.
	Repo: closed source
*/
#include <a_samp>

/*
	fixes
	By Y-Less & co.
	Repo: https://github.com/pawn-lang/sa-mp-fixes
*/
#include <vendor/fixes/fixes>

/*
	ugmp
	By the UGMP team.
	Repo: closed source
*/
#include <ugmp>
